global:
  checkNewVersion: false
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

log:
  level: "DEBUG"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    watch: false

  file:
    directory: "/etc/traefik/dynamic/"
    watch: true
    debugLogGeneratedTemplate: true
  