global:
  checkNewVersion: false
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"

  mssql:
    address: ":1433"

log:
  level: "DEBUG"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    watch: false

  file:
    directory: "/etc/traefik/dynamic/"
    watch: true
    debugLogGeneratedTemplate: true

tracing:
  jaeger:
    samplingServerURL: http://127.0.0.1:5778/sampling
